// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_tqhezg1v2Xc7ekJEMtB3gaJn0ayMLA',
    appId: '1:685472580437:web:e953e2315f49c9f74ca5dc',
    messagingSenderId: '685472580437',
    projectId: 'doctor-booking-3ee1a',
    authDomain: 'doctor-booking-3ee1a.firebaseapp.com',
    storageBucket: 'doctor-booking-3ee1a.firebasestorage.app',
    measurementId: 'G-1LMRCY2282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJr_9Yx8Wd7FyKXzU-6WaZB-v5KlH7Ng8',
    appId: '1:685472580437:android:51e5a19c3261616b4ca5dc',
    messagingSenderId: '685472580437',
    projectId: 'doctor-booking-3ee1a',
    storageBucket: 'doctor-booking-3ee1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp2PrMSJTEZyhS6tCQS5ZASHB7OVboR5Q',
    appId: '1:685472580437:ios:208debd9624d7f044ca5dc',
    messagingSenderId: '685472580437',
    projectId: 'doctor-booking-3ee1a',
    storageBucket: 'doctor-booking-3ee1a.firebasestorage.app',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp2PrMSJTEZyhS6tCQS5ZASHB7OVboR5Q',
    appId: '1:685472580437:ios:208debd9624d7f044ca5dc',
    messagingSenderId: '685472580437',
    projectId: 'doctor-booking-3ee1a',
    storageBucket: 'doctor-booking-3ee1a.firebasestorage.app',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_tqhezg1v2Xc7ekJEMtB3gaJn0ayMLA',
    appId: '1:685472580437:web:b7aa7ae692a05c4f4ca5dc',
    messagingSenderId: '685472580437',
    projectId: 'doctor-booking-3ee1a',
    authDomain: 'doctor-booking-3ee1a.firebaseapp.com',
    storageBucket: 'doctor-booking-3ee1a.firebasestorage.app',
    measurementId: 'G-3BD0B4VNQY',
  );
}
