// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNi4rXP5-_HBqJxJqEx_7u3WRXI3DHrc',
    appId: '1:887995098539:web:e299a120be8bd6bf7d1eee',
    messagingSenderId: '887995098539',
    projectId: 'rolebase',
    authDomain: 'rolebase.firebaseapp.com',
    storageBucket: 'rolebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PWW0JzhScUW1DYB-xoyRNiqKs52W0c8',
    appId: '1:887995098539:android:46706a649c3e7e267d1eee',
    messagingSenderId: '887995098539',
    projectId: 'rolebase',
    storageBucket: 'rolebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5to1-KIWubqeOtDVPEsR_QQi5Q-TaFCw',
    appId: '1:887995098539:ios:7239a903d9e167487d1eee',
    messagingSenderId: '887995098539',
    projectId: 'rolebase',
    storageBucket: 'rolebase.firebasestorage.app',
    iosBundleId: 'com.example.mutliRole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5to1-KIWubqeOtDVPEsR_QQi5Q-TaFCw',
    appId: '1:887995098539:ios:7239a903d9e167487d1eee',
    messagingSenderId: '887995098539',
    projectId: 'rolebase',
    storageBucket: 'rolebase.firebasestorage.app',
    iosBundleId: 'com.example.mutliRole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNi4rXP5-_HBqJxJqEx_7u3WRXI3DHrc',
    appId: '1:887995098539:web:b234e53826d7d2667d1eee',
    messagingSenderId: '887995098539',
    projectId: 'rolebase',
    authDomain: 'rolebase.firebaseapp.com',
    storageBucket: 'rolebase.firebasestorage.app',
  );
}
