// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVmUx4scD2PnWPavb3bguSPHM6922wH8',
    appId: '1:19188899599:web:f938536e2c100047b9287a',
    messagingSenderId: '19188899599',
    projectId: 'testing-client-e7128',
    authDomain: 'testing-client-e7128.firebaseapp.com',
    storageBucket: 'testing-client-e7128.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8EqG7-EGIB0wnnR6ly-57NAlprPGue8',
    appId: '1:19188899599:android:cdd2a7f0698bdde7b9287a',
    messagingSenderId: '19188899599',
    projectId: 'testing-client-e7128',
    storageBucket: 'testing-client-e7128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgyn_FKOR_OJP7L_DeIox19HqfZ8tkzw',
    appId: '1:19188899599:ios:94f0cb04c65dd8bbb9287a',
    messagingSenderId: '19188899599',
    projectId: 'testing-client-e7128',
    storageBucket: 'testing-client-e7128.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQgyn_FKOR_OJP7L_DeIox19HqfZ8tkzw',
    appId: '1:19188899599:ios:94f0cb04c65dd8bbb9287a',
    messagingSenderId: '19188899599',
    projectId: 'testing-client-e7128',
    storageBucket: 'testing-client-e7128.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyVmUx4scD2PnWPavb3bguSPHM6922wH8',
    appId: '1:19188899599:web:de274172165ecf11b9287a',
    messagingSenderId: '19188899599',
    projectId: 'testing-client-e7128',
    authDomain: 'testing-client-e7128.firebaseapp.com',
    storageBucket: 'testing-client-e7128.firebasestorage.app',
  );
}
